= Überblick
:allow-uri-read: 




== Überblick

_Include/todo/Management.command_center.operations.add_existing_server_to_company.adoc _include/todo/Management.command_center.operations.allow_new_AVD_connections.adoc _include/todo/Management.command_center.operations.backup_list.adoc _todo/todo/Management.command_center.operations.backup_restore_to_drive.adoc _include/Management.command_center.operations.backup_server_now.adoc_todo/Management.command_center.operations.backups_run_all_scheduled.adoc_todo/include_Management.command_center.operations.change_data_home_pro_folders.adoc/include_todo/Management.command_center.operations.change_password.adoc/include_todo/Management.command_center.operations.copy_template_to_gallery.adoc_todo/Management.command_center.operations.create_azure_file_share.adoc_todo/include/Management.command_center.operations.create_cache_company.adoc_todo/include/Management.command_center.operations.create_azure_netapp_files_share.adoc/include_Management.command_center.operations.create_data_center_site.adoc_todo/include/Management.command_center.operations.create_server_from_backup.adoc_Management.command_center.operations.create_server_from_clone.adoc/include/include_todo_Management.command_center.operations.create_no_server_company.adoc/include/include_Management.command_center.operations.create_template_phase_1.adoc_todo/include/include_Management.command_center.operations.delete_backup.adoc_Management.command_center.operations.create_template_phase_3.adoc_todo/include/include/include_Management.command_center.operations.delete_datacenter_site.adoc_todo/include_Management.command_center.operations.create_server_from_template.adoc/include_Management.command_center.operations.delete_server.adoc_Management.command_center.operations.delete_template.adoc_todo/include/include/include/include_Management.command_center.operations.created_company.adoc/Management.command_center.operations.edit_resource_pool.adoc_todo/include_todo/include/include_todo/include_Management.command_center.operations.edit_workload_schedule.adoc_Management.command_center.operations.file_migration.adoc_Management.command_center.operations.delete_drives_from_server.adoc Management.command_center.operations.edit_provisioning_collection.adoc Management.command_center.operations.exclude_server_from_monitoring.adoc Management.command_center.operations.generate_email_reports.adoc Management.command_center.operations.install_thinprint_license_server.adoc/include_todo/include_Management.command_center.operations.expand_drive.adoc Management.command_center.operations.generate_reports.adoc Management.command_center.operations.list_drives_for_server.adoc_Management.command_center.operations.install_notepad++_Chrome.adoc_Management.command_center.operations.list_long_running_operations.adoc Management.command_center.operations.load_active_users.adoc Management.command_center.operations.load_cache_companies.adoc Management.command_center.operations.load_hypervisor_config_options.adoc Management.command_center.operations.load_hypervisor_type.adoc Management.command_center.operations.load_machine_series.adoc Management.command_center.operations.load_machine_sizes.adoc Management.command_center.operations.load_max_concurrent_users.adoc Management.command_center.operations.load_resource_pool_data.adoc Management.command_center.operations.load_server_resource_report_data.adoc Management.command_center.operations.load_servers_for_company.adoc Management.command_center.operations.load_storage_types.adoc Management.command_center.operations.load_templates.adoc Management.command_center.operations.load_virtual_machines.adoc _Include/todo/Management.command_center.operations.make_server_active.adoc _include/todo/Management.command_center.operations.make_server_data_server.adoc _include/todo/Management.command_center.operations.migrate_company.adoc _include/todo/Management.command_center.operations.move_servers_to_company.adoc _include/todo/Management.command_center.operations.reboot_server.adoc_todo/Management.command_center.operations.reload_configuration.adoc_include/todo/Management.command_center.operations.reload_monitored_applications.adoc_todo/include_Management.command_center.operations.resource_allocation_enable.adoc/include_Management.command_center.operations.rename_server.adoc/include_todo/Management.command_center.operations.remove_vds_software.adoc/include_Management.command_center.operations.run_daily_maintenance.adoc/include_Management.command_center.operations.run_program.adoc/include_todo/include/Management.command_center.operations.run_daily_actions.adoc/Management.command_center.operations.run_workload_schedule.adoc_Management.command_center.operations.set_external_dns.adoc/include_todo/include_Management.command_center.operations.should_pool_be_running.adoc/include_include_Management.command_center.operations.run_resource_allocation.adoc/include_Management.command_center.operations.set_time_zone.adoc_include_include/include/include_Management.command_center.operations.start_server_for_wake_on_demand.adoc_Management.command_center.operations.start_server.adoc/include_Management.command_center.operations.stop_sddc.adoc/include/include_Management.command_center.operations.set_gateway_address.adoc/include_Management.command_center.operations.stop_cwagent.adoc_todo/include/include_include_Management.command_center.operations.test_hypervisor_connection.adoc_Management.command_center.operations.update_active_user_count.adoc/include_Management.command_center.operations.start_company.adoc Management.command_center.operations.stop_company.adoc Management.command_center.operations.stop_server.adoc Management.command_center.operations.update_cw_vm_automation_service.adoc/include_Management.command_center.operations.wildcard_cert_install.adoc/include_include/include_to/include_include/include_Management.command_center.operations.wildcard_cert_create_new.adoc_to/include
